### ISSUE TITLE
Why you are not reusing resque web server (monitoring) and writing your own?

### ISSUE THREAD

**Issue by lexer** [groupme/pace#1]

**Comment by cmdrkeene** [comment]
we totally should be. I'll swap it out today :)

Brandon

**Comment by cmdrkeene** [comment]
Err, that was meant for the em-hiredis issue.

As far as I know, resque web monitoring does not provide 1) load average and 2) historical throughput. Please let me know if there's something I missed :)

It's very important for us operationally to know peak capacity/load because we use this for capacity planning (adding more upstream resources).

Historical monitoring is important for us because we use it to forecast traffic and run aberration detection (similar to RRDTool). I'd actually like to add an instrument for RRDTool support, but our current environment doesn't support RRDTool too well.

**Comment by daveyeu** [comment]
So... the Resque panel has been removed on master. As such I'm closing this out.
